// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3wE4T9yoyeNOE6CKDVLxQp7dKDAC13wQ',
    appId: '1:35321658484:web:b181d996b8ad5ebc4de521',
    messagingSenderId: '35321658484',
    projectId: 'directory-f4147',
    authDomain: 'directory-f4147.firebaseapp.com',
    storageBucket: 'directory-f4147.firebasestorage.app',
    measurementId: 'G-25HGR08NF6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_VgGTxivKKS4uGN_l9-ZZKVTHiqMAy_c',
    appId: '1:35321658484:android:d3db0b044371a6c64de521',
    messagingSenderId: '35321658484',
    projectId: 'directory-f4147',
    storageBucket: 'directory-f4147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcb3vSwaxS7TwvuH0hQ0QYdkX1Lpy3b3Y',
    appId: '1:35321658484:ios:c401f433882537d94de521',
    messagingSenderId: '35321658484',
    projectId: 'directory-f4147',
    storageBucket: 'directory-f4147.firebasestorage.app',
    iosBundleId: 'com.example.studentdirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcb3vSwaxS7TwvuH0hQ0QYdkX1Lpy3b3Y',
    appId: '1:35321658484:ios:c401f433882537d94de521',
    messagingSenderId: '35321658484',
    projectId: 'directory-f4147',
    storageBucket: 'directory-f4147.firebasestorage.app',
    iosBundleId: 'com.example.studentdirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3wE4T9yoyeNOE6CKDVLxQp7dKDAC13wQ',
    appId: '1:35321658484:web:aa143690587ad78d4de521',
    messagingSenderId: '35321658484',
    projectId: 'directory-f4147',
    authDomain: 'directory-f4147.firebaseapp.com',
    storageBucket: 'directory-f4147.firebasestorage.app',
    measurementId: 'G-RFPT6DZZ7Z',
  );
}
